### ISSUE TITLE
[BUG] backend is trying to connect to 5435 with docker-compose.dev.yml

### ISSUE THREAD

**Issue by rsohlot** [chaos-genius/chaos_genius#832]
On setting up the project by executing the following command:
```
docker-compose -f "docker-compose.dev.yml" up -d --build
```
Getting the following error in chaosgenius-server logs:
```
Traceback (most recent call last):

  File "/usr/local/bin/flask", line 8, in <module>

    sys.exit(main())

  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 990, in main

    cli.main(args=sys.argv[1:])

  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 596, in main

    return super().main(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main

    rv = self.invoke(ctx)

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke

    return _process_result(sub_ctx.command.invoke(sub_ctx))

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke

    return ctx.invoke(self.callback, **ctx.params)

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke

    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func

    return f(get_current_context(), *args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/flask/cli.py", line 440, in decorator

    return __ctx.invoke(f, *args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke

    return __callback(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/cli.py", line 136, in upgrade

    _upgrade(directory, revision, sql, tag, x_arg)

  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 96, in wrapped

    f(*args, **kwargs)

  File "/usr/local/lib/python3.8/dist-packages/flask_migrate/__init__.py", line 271, in upgrade

    command.upgrade(config, revision, sql=sql, tag=tag)

  File "/usr/local/lib/python3.8/dist-packages/alembic/command.py", line 320, in upgrade

    script.run_env()

  File "/usr/local/lib/python3.8/dist-packages/alembic/script/base.py", line 563, in run_env

    util.load_python_file(self.dir, "env.py")

  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 92, in load_python_file

    module = load_module_py(module_id, path)

  File "/usr/local/lib/python3.8/dist-packages/alembic/util/pyfiles.py", line 108, in load_module_py

    spec.loader.exec_module(module)  # type: ignore

  File "<frozen importlib._bootstrap_external>", line 848, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/usr/src/app/migrations/env.py", line 91, in <module>

    run_migrations_online()

  File "/usr/src/app/migrations/env.py", line 75, in run_migrations_online

    with connectable.connect() as connection:

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3166, in connect

    return self._connection_cls(self, close_with_result=close_with_result)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 96, in __init__

    else engine.raw_connection()

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3245, in raw_connection

    return self._wrap_pool_connect(self.pool.connect, _connection)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3215, in _wrap_pool_connect

    Connection._handle_dbapi_exception_noconnection(

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 2068, in _handle_dbapi_exception_noconnection

    util.raise_(

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_

    raise exception

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 3212, in _wrap_pool_connect

    return fn()

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 301, in connect

    return _ConnectionFairy._checkout(self)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 761, in _checkout

    fairy = _ConnectionRecord.checkout(pool)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 419, in checkout

    rec = pool._do_get()

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 145, in _do_get

    self._dec_overflow()

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

    compat.raise_(

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_

    raise exception

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/impl.py", line 142, in _do_get

    return self._create_connection()

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 247, in _create_connection

    return _ConnectionRecord(self)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 362, in __init__

    self.__connect()

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 605, in __connect

    pool.logger.debug("Error on connect(): %s", e)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__

    compat.raise_(

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 211, in raise_

    raise exception

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/pool/base.py", line 599, in __connect

    connection = pool._invoke_creator(self)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/create.py", line 578, in connect

    return dialect.connect(*cargs, **cparams)

  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 584, in connect

    return self.dbapi.connect(*cargs, **cparams)

  File "/usr/local/lib/python3.8/dist-packages/psycopg2/__init__.py", line 127, in connect

    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)

sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not connect to server: Connection refused

Is the server running on host "192.168.18.9" and accepting

TCP/IP connections on port 5435?
```

## Environment
-  Branch : develop
- **OS Version / Instance**: Windows 10, Docker version: version 4.5.1
- **Deployment type**: Docker commpose

**Comment by Samyak2** [comment]
Hi @rsohlot, the connection details are taken from the `.env` file. Can you check that you have not modified this file?

**Comment by Samyak2** [comment]
Found the issue over a call. The `.env.local` files was being copied inside the dev containers and that file had the port set to `5435`. Closing this as it's not a real issue. See #876 for the reasoning behind not adding `.env.local` to `.dockerignore`.

cc: @rjdp
