### ISSUE TITLE
Error in Analytics: KeyError: 'scheduler_frequency'

### ISSUE THREAD

**Issue by rjdp** [chaos-genius/chaos_genius#899]
# Error Report

An error was caught when running analytics.
Exception message: `KeyError: 'scheduler_frequency'`

## Environment

- **Instance/System type**: 
- **Chaos Genius version**: 0.5.2-latest-thirdparty-compose
- **OS Version**: Linux-5.13.0-1019-aws-x86_64-with-glibc2.29
- **Deployment type**: Docker (inferred)
- **Python version**: 3.8.10

## Additional information

<details>
  <summary>Exception traceback</summary>

  ```
  Traceback (most recent call last):
  File "/usr/src/app/chaos_genius/jobs/anomaly_tasks.py", line 80, in anomaly_single_kpi
    run_anomaly_for_kpi(kpi_id, end_date, task_id=task_id)
  File "/usr/src/app/chaos_genius/controllers/kpi_controller.py", line 59, in run_anomaly_for_kpi
    if end_date is None and kpi_info["scheduler_params"]["scheduler_frequency"] == "D":
KeyError: 'scheduler_frequency'

  ```

</details>

<details>
  <summary>KPI Info</summary>

  ```
  {'active': True,
 'aggregation': 'count',
 'anomaly_frequency': None,
 'anomaly_params': {'anomaly_period': 60,
                    'frequency': 'D',
                    'model_name': 'ProphetModel',
                    'sensitivity': 'medium'},
 'created_at': datetime.datetime(2022, 4, 7, 6, 55, 28, 946855),
 'data_source': 3,
 'datetime_column': 'date',
 'dimensions': ['main_artist', 'artists'],
 'id': 2,
 'is_certified': False,
 'is_static': False,
 'kpi_query': '',
 'kpi_type': 'table',
 'metric': 'streams',
 'name': 'Spotify',
 'run_anomaly': True,
 'scheduler_params': {'anomaly_status': 'in-progress',
                      'last_scheduled_time_anomaly': '2022-04-07T06:56:38.730515',
                      'last_scheduled_time_rca': '2022-04-07T06:56:07.816806',
                      'rca_status': 'in-progress',
                      'time': '06:00:00'},
 'schema_name': 'public',
 'static_params': None,
 'table_name': 'spotify_12m',
 'timezone_aware': True}
  ```

</details>

<details>
  <summary>Data Source Info</summary>

  ```
  {'active': True,
 'connection_status': 'connected',
 'connection_type': 'Snowflake',
 'created_at': datetime.datetime(2022, 4, 7, 5, 24, 23, 592005),
 'database_timezone': 'UTC',
 'id': 3,
 'is_third_party': False,
 'last_sync': datetime.datetime(2022, 4, 7, 5, 24, 33, 797409),
 'name': 'SnowFlake',
 'sync_status': 'Completed'}
  ```

</details>

**Comment by Samyak2** [comment]
Should be fixed by #903
